apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: examples-voting-service
  annotations:
    backstage.io/kubernetes-id: examples-voting-service
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: guests
  lifecycle: experimental