site_name: Voting App Service Documentation

nav:
  - Home: index.md
  - Architecture: architecture.md
  - API Reference: N/A

docs_dir: docs

plugins:
  - techdocs-core # This plugin is required for Backstage compatibility