apiVersion: v1
kind: Service
metadata:
  name: {{ include "example-voting-app.fullname" . }}
  labels:
    app: {{ include "example-voting-app.name" . }}
    backstage.io/kubernetes-id: {{ .Values.backstage.label }}   
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: {{ include "example-voting-app.name" . }}
    backstage.io/kubernetes-id: {{ .Values.backstage.label }}    
