apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "example-voting-app.fullname" . }}
  annotations:
    backstage.io/kubernetes-id: {{ .Values.backstage-annotation-and-label }}
  labels:
    app: {{ include "example-voting-app.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "example-voting-app.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "example-voting-app.name" . }}
        backstage.io/kubernetes-id: {{ .Values.backstage-annotation-and-label }}
    spec:
      containers:
        - name: example-voting-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 80
          imagePullPolicy: {{ .Values.image.pullPolicy }}
